version: '3'
services:
  db:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/app
    environment:
      - PG_HOST=db
    ports:
      - "3000:3000"
    depends_on:
      - db